version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd api
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - api/target/api-0.0.1-SNAPSHOT.war
