version: 0.0
os: linux
files:
  - source: /target/api-0.0.1-SNAPSHOT.war
    destination: /usr/share/tomcat/webapps
hooks:
  BeforeInstall:
    - location: scripts/preinstall.sh
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3600